/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apress.swig;

public class Unix implements UnixConstants {
  public static long getuid() {
    return UnixJNI.getuid();
  }

  public static void setCounter(int value) {
    UnixJNI.counter_set(value);
  }

  public static int getCounter() {
    return UnixJNI.counter_get();
  }

  public static int getReadOnly() {
    return UnixJNI.readOnly_get();
  }

  public static void setReadWriter(int value) {
    UnixJNI.readWriter_set(value);
  }

  public static int getReadWriter() {
    return UnixJNI.readWriter_get();
  }

}
