/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apress.swig;

public class UnixJNI {
  public final static native long getuid();
  public final static native void counter_set(int jarg1);
  public final static native int counter_get();
  public final static native int MAX_WIDTH_get();
  public final static native int MAX_HEIGHT_get();
  public final static native int readOnly_get();
  public final static native void readWriter_set(int jarg1);
  public final static native int readWriter_get();
  public final static native int one_get();
  public final static native int two_get();
  public final static native int three_get();
}
