/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apress.swig;

public class UnixJNI {
  public final static native long getuid();
  public final static native void counter_set(int jarg1);
  public final static native int counter_get();
  public final static native int MAX_WIDTH_get();
  public final static native int MAX_HEIGHT_get();
  public final static native int readOnly_get();
  public final static native void readWriter_set(int jarg1);
  public final static native int readWriter_get();
  public final static native int one_get();
  public final static native int two_get();
  public final static native int three_get();
  public final static native int Sunday_get();
  public final static native int Sun_get();
  public final static native void Point_x_set(long jarg1, Point jarg1_, int jarg2);
  public final static native int Point_x_get(long jarg1, Point jarg1_);
  public final static native void Point_y_set(long jarg1, Point jarg1_, int jarg2);
  public final static native int Point_y_get(long jarg1, Point jarg1_);
  public final static native long new_Point();
  public final static native void delete_Point(long jarg1);
}
