/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apress.swig;

public interface UnixConstants {
  public final static int MAX_WIDTH = UnixJNI.MAX_WIDTH_get();
  public final static int MAX_HEIGHT = UnixJNI.MAX_HEIGHT_get();
  public final static int one = UnixJNI.one_get();
  public final static int two = UnixJNI.two_get();
  public final static int three = UnixJNI.three_get();


}
